apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo
data:
  NODE_ENV: "production"
  # Internal cluster URLs
  DATABASE_URL: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres.demo.svc.cluster.local:5432/$(POSTGRES_DB)"
  REDIS_URL: "redis://redis.demo.svc.cluster.local:6379"
